[package]
name = "hp-microservice"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
prost = "0.13.5"
tonic = "0.13.0"

[build-dependencies]
tonic-build = "*"
